### ISSUE TITLE
I can't import #include "kiss_fft.h" in my native-lib.c

### ISSUE THREAD

**Issue by HerlanAssis** [berndporr/kiss-fft#1]
I follow all steps and import as "compile project(":jnifft-debug")" but can't import '#include "kissfft.h"'. Any solution?

**Comment by berndporr** [comment]
How about:
compile project(":jnifft-release")

**Comment by HerlanAssis** [comment]
I generated the release version and imported it as 'compile project (': jnifft-release ')'
![erroinclude](https://user-images.githubusercontent.com/13255309/41289191-5cbe8da8-6e1f-11e8-9551-82742d546654.png)

however the error continues.
![erroinclude0](https://user-images.githubusercontent.com/13255309/41289208-6983b2f2-6e1f-11e8-985b-8970f8bd8f4f.png)

**Comment by berndporr** [comment]
I see that you are trying to create a JNI wrapper.
However, jnifft IS a wrapper around the C library and creates a JAVA class. If you want to write your own wrapper then use the orignal kiss fft and do it by yourself. No need to use this code here.
Check out for example FFTTest how to use the wrapper:
```
       kissFastFourierTransformer = new KISSFastFourierTransformer();
        final int testsize = 64;
        double[] indata = new double[testsize];
        for (int i = 0; i < testsize; i++) indata[i] = Math.random() - 0.5;
        Complex[] outdata1 = kissFastFourierTransformer.transform(indata);
```

**Comment by HerlanAssis** [comment]
I understand, in this case all I have to do is import the 'kiss_fft.' Libraries so:
![fftw](https://user-images.githubusercontent.com/13255309/41324360-7bbc4fb8-6e8a-11e8-8729-1cf793addcb3.png)


and create my own wrapper, right ?.

**Comment by berndporr** [comment]
Yes

**Comment by HerlanAssis** [comment]
Thanks for helping! :D

**Comment by berndporr** [comment]
Pleasure! :)
