### ISSUE TITLE
the number of samples

### ISSUE THREAD

**Issue by k-hengzhou** [berndporr/kiss-fft#2]
Does the number of samples of frequency domain must less than the the number of samples of frequency domain. 
when I  Run the following program
kiss_fft_cfg cfg = kiss_fft_alloc( 1024, 0, 0, 0 );
kiss_fft_cpx *cx_in = new kiss_fft_cpx[400];
kiss_fft_cpx *cx_out = new kiss_fft_cpx[1024];
the value of ou is -nan.
sorry for My native language is not English.

**Comment by berndporr** [comment]
Generally if you have an N point discrete Fourier Transform then that's the case both in the time- and frequency domain:
```
const int n = 1024;
kiss_fft_cfg cfg = kiss_fft_alloc( n, 0, 0, 0 );
kiss_fft_cpx *cx_in = new kiss_fft_cpx[n];
kiss_fft_cpx *cx_out = new kiss_fft_cpx[n];
```
Sample numbers need to be exactly identical.
(see the README of this project)
