### ISSUE TITLE
Unable to set FFT datatype to short

### ISSUE THREAD

**Issue by abu100** [berndporr/kiss-fft#3]
Hey,
I have been trying to set the FFT datatype to short instead of the default double.
I commented #add_definitions(-Dkiss_fft_scalar=double) in the jnifft/cmakelist.txt and instead added add_definitions(-DFIXED_POINT=16) but it produces errors when I build it. Do I have to change the wrapper as well? 

Errors:
Caused by: Build command failed.
Error while executing process D:\HammadSdk\cmake\3.6.4111459\bin\cmake.exe with arguments {--build C:\Users\Confu008\Desktop\kissfft\jnifft\.externalNativeBuild\cmake\debug\x86_64 --target kiss-fft-lib}
[1/4] Building CXX object CMakeFiles/kiss-fft-lib.dir/src/main/cpp/kiss-fft-lib.cpp.o
[2/4] Building C object CMakeFiles/kiss-fft-lib.dir/C_/Users/Confu008/Desktop/kissfft/kiss_fft.c.o
[3/4] Building C object CMakeFiles/kiss-fft-lib.dir/C_/Users/Confu008/Desktop/kissfft/kiss_fftr.c.o
FAILED: D:\HammadSdk\ndk-bundle\toolchains\llvm\prebuilt\windows-x86_64\bin\clang++.exe  --target=x86_64-none-linux-android21 --gcc-toolchain=D:/HammadSdk/ndk-bundle/toolchains/llvm/prebuilt/windows-x86_64 --sysroot=D:/HammadSdk/ndk-bundle/toolchains/llvm/prebuilt/windows-x86_64/sysroot  -DFIXED_POINT=16 -Dkiss_fft_lib_EXPORTS  -g -DANDROID -fdata-sections -ffunction-sections -funwind-tables -fstack-protector-strong -no-canonical-prefixes -fno-addrsig -Wa,--noexecstack -Wformat -Werror=format-security   -O0 -fno-limit-debug-info  -fPIC -MD -MT CMakeFiles/kiss-fft-lib.dir/src/main/cpp/kiss-fft-lib.cpp.o -MF CMakeFiles\kiss-fft-lib.dir\src\main\cpp\kiss-fft-lib.cpp.o.d -o CMakeFiles/kiss-fft-lib.dir/src/main/cpp/kiss-fft-lib.cpp.o -c C:\Users\Confu008\Desktop\kissfft\jnifft\src\main\cpp\kiss-fft-lib.cpp
C:\Users\Confu008\Desktop\kissfft\jnifft\src\main\cpp\kiss-fft-lib.cpp:122:5: error: no matching function for call to 'kiss_fftr'

    kiss_fftr(cfg, values, outArray);

C:\Users\Confu008\Desktop\kissfft\jnifft\src\main\cpp/../../../../kiss_fftr.h:29:6: note: candidate function not viable: no known conversion from 'double *' to 'const int16_t *' (aka 'const short *') for 2nd argument

void kiss_fftr(kiss_fftr_cfg cfg,const kiss_fft_scalar *timedata,kiss_fft_cpx *freqdata);

C:\Users\Confu008\Desktop\kissfft\jnifft\src\main\cpp\kiss-fft-lib.cpp:190:5: error: no matching function for call to 'kiss_fftri'

    kiss_fftri(cfg, inArray, outValues);

C:\Users\Confu008\Desktop\kissfft\jnifft\src\main\cpp/../../../../kiss_fftr.h:35:6: note: candidate function not viable: no known conversion from 'double *' to 'int16_t *' (aka 'short *') for 3rd argument

void kiss_fftri(kiss_fftr_cfg cfg,const kiss_fft_cpx *freqdata,kiss_fft_scalar *timedata);

2 errors generated.

ninja: build stopped: subcommand failed.

	at com.android.build.gradle.internal.cxx.process.ProcessOutputJunction.execute(ProcessOutputJunction.kt:78)
	at com.android.build.gradle.internal.cxx.process.ProcessOutputJunction.execute(ProcessOutputJunction.kt:119)
	at com.android.build.gradle.tasks.ExternalNativeBuildTask.executeProcessBatch(ExternalNativeBuildTask.java:327)
	at com.android.build.gradle.tasks.ExternalNativeBuildTask.build(ExternalNativeBuildTask.java:195)
	at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:73)
	... 125 more

**Comment by berndporr** [comment]
As you see the wrapper for JNI is written purely for double.
Mobile phones have a floating point unit and there is no gain in speed between int and float/double so the wrapper is only for double. There is even no difference between float and double nowadays.

The pure C version also works with integer with `add_definitions(-DFIXED_POINT=16)` in CMakeLists:

```
bp1@bp1-ThinkPad-X220:~/sandbox/kiss-fft$ make
Scanning dependencies of target kiss-fft
[ 33%] Building C object CMakeFiles/kiss-fft.dir/kiss_fft.c.o
[ 66%] Building C object CMakeFiles/kiss-fft.dir/kiss_fftr.c.o
[100%] Linking C static library libkiss-fft.a
[100%] Built target kiss-fft
bp1@bp1-ThinkPad-X220:~/sandbox/kiss-fft$ 
```

For JNI just leave it as double and it will compile. Tested under Linux.
