### ISSUE TITLE
current "relation" to https://github.com/mborgerding/kissfft

### ISSUE THREAD

**Issue by jerabaul29** [berndporr/kiss-fft#5]
You mention that:

"
This is a fork, stripped down and further debugged version of the original kiss-fft library by Mark Borgerding Mark@Borgerding.net.
"

- would you be confident to recommend me using your code as a new user?
- as an end user, what do you think would be the advantages for me using this code rather than the original one?

**Comment by berndporr** [comment]
Not sure what you mean with "new user" but you need to understand how Fourier Transforms work. The original code is more complex to use but has more options.
